<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="3" failed="1" ignored="0" total="4" passed="0">
  <reporter-output>
  </reporter-output>
  <suite name="Suite" duration-ms="176" started-at="2022-10-31T00:28:05 IST" finished-at="2022-10-31T00:28:05 IST">
    <groups>
      <group name="confirm">
        <method signature="testdepends.confirm()[pri:0, instance:dependsOn.testdepends@4b1c1ea0]" name="confirm" class="dependsOn.testdepends"/>
      </group> <!-- confirm -->
      <group name="buyNow">
        <method signature="testdepends.buyNow()[pri:0, instance:dependsOn.testdepends@4b1c1ea0]" name="buyNow" class="dependsOn.testdepends"/>
      </group> <!-- buyNow -->
      <group name="select">
        <method signature="testdepends.select()[pri:0, instance:dependsOn.testdepends@4b1c1ea0]" name="select" class="dependsOn.testdepends"/>
      </group> <!-- select -->
      <group name="checkout">
        <method signature="testdepends.checkout()[pri:0, instance:dependsOn.testdepends@4b1c1ea0]" name="checkout" class="dependsOn.testdepends"/>
      </group> <!-- checkout -->
    </groups>
    <test name="testdepends" duration-ms="176" started-at="2022-10-31T00:28:05 IST" finished-at="2022-10-31T00:28:05 IST">
      <class name="dependsOn.testdepends">
        <test-method status="FAIL" signature="select()[pri:0, instance:dependsOn.testdepends@4b1c1ea0]" name="select" duration-ms="30" started-at="2022-10-31T00:28:05 IST" finished-at="2022-10-31T00:28:05 IST">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[null]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: null
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.fail(Assert.java:106)
at dependsOn.testdepends.select(testdepends.java:14)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.ArrayList.forEach(ArrayList.java:1249)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- select -->
        <test-method status="SKIP" signature="buyNow()[pri:0, instance:dependsOn.testdepends@4b1c1ea0]" name="buyNow" duration-ms="0" depends-on-groups="select" started-at="2022-10-31T00:28:05 IST" finished-at="2022-10-31T00:28:05 IST">
          <exception class="java.lang.Throwable">
            <message>
              <![CDATA[Method testdepends.buyNow()[pri:0, instance:dependsOn.testdepends@4b1c1ea0] depends on not successfully finished methods in group "select"]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.Throwable: Method testdepends.buyNow()[pri:0, instance:dependsOn.testdepends@4b1c1ea0] depends on not successfully finished methods in group "select"
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:102)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.ArrayList.forEach(ArrayList.java:1249)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.Throwable -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- buyNow -->
        <test-method status="SKIP" signature="checkout()[pri:0, instance:dependsOn.testdepends@4b1c1ea0]" name="checkout" duration-ms="0" depends-on-groups="buyNow" started-at="2022-10-31T00:28:05 IST" finished-at="2022-10-31T00:28:05 IST">
          <exception class="java.lang.Throwable">
            <message>
              <![CDATA[Method testdepends.checkout()[pri:0, instance:dependsOn.testdepends@4b1c1ea0] depends on not successfully finished methods in group "buyNow"]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.Throwable: Method testdepends.checkout()[pri:0, instance:dependsOn.testdepends@4b1c1ea0] depends on not successfully finished methods in group "buyNow"
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:102)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.ArrayList.forEach(ArrayList.java:1249)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.Throwable -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- checkout -->
        <test-method status="SKIP" signature="confirm()[pri:0, instance:dependsOn.testdepends@4b1c1ea0]" name="confirm" duration-ms="0" depends-on-groups="checkout" started-at="2022-10-31T00:28:05 IST" finished-at="2022-10-31T00:28:05 IST">
          <exception class="java.lang.Throwable">
            <message>
              <![CDATA[Method testdepends.confirm()[pri:0, instance:dependsOn.testdepends@4b1c1ea0] depends on not successfully finished methods in group "checkout"]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.Throwable: Method testdepends.confirm()[pri:0, instance:dependsOn.testdepends@4b1c1ea0] depends on not successfully finished methods in group "checkout"
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:102)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.ArrayList.forEach(ArrayList.java:1249)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.Throwable -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- confirm -->
      </class> <!-- dependsOn.testdepends -->
    </test> <!-- testdepends -->
  </suite> <!-- Suite -->
</testng-results>
